- name: Installer nftables
  apt:
    name: nftables
    state: present
    update_cache: yes



- name: Deployer configuration nftables
  copy:
    dest: /etc/nftables.conf
    content: |
      flush ruleset

      table inet filter {
        chain input {
          type filter hook input priority 0;
          policy drop;

          iif lo accept
          ct state established,related accept

          tcp dport 22 ip saddr 192.168.1.0/24 accept
          tcp dport 80 accept
          tcp dport 443 accept
          udp dport 47512 accept
        }

        chain forward {
          type filter hook forward priority 0;
          policy drop;
          ct state established,related accept;

        }

        chain output {
          type filter hook output priority 0;
          policy accept;
        }
      }


- name: Activation nftables
  systemd:
    name: nftables
    enabled: yes
    state: started
  notify: Restart nftables
